name: Registry Sync

on:
  push:
    branches:
      - main
    tags:
      - "**"
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  emit-resync:
    name: emit-resync
    runs-on: meld-ubuntu-lts
    steps:
      - name: Emit resync event
        uses: peter-evans/repository-dispatch@v3
        with:
          app_id: ${{ secrets.MELD_TOKEN_REGISTRY_SYNC_APP_ID }}
          private_key: ${{ secrets.MELD_TOKEN_REGISTRY_SYNC_PRIVATE_KEY }}
          repository: MELD-labs/token-registry-sync
          event-type: resync-event
          client-payload: 'test'